In [27]:
import scipy
import scipy.linalg   # SciPy Linear Algebra Library
import numpy as np

def dd(X):
    D = np.diag(np.abs(X)) # Find diagonal coefficients
    S = np.sum(np.abs(X), axis=1) - D # Find row sum without diagonal
    if np.all(D > S):
        print('matrix is diagonally dominant')
    else:
        print('NOT diagonally dominant')
    return


A = np.array([[8,4,-1],[-2,5,1],[2,-1,6]])
dd(A);
P, L, U = scipy.linalg.lu(A)

print("A:")
print(A)

print("P:")
print(P)

print("L:")
print(L)

print("U:")
print(U)

matrix is diagonally dominant
A:
[[ 8  4 -1]
 [-2  5  1]
 [ 2 -1  6]]
P:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
L:
[[ 1.          0.          0.        ]
 [-0.25        1.          0.        ]
 [ 0.25       -0.33333333  1.        ]]
U:
[[ 8.    4.   -1.  ]
 [ 0.    6.    0.75]
 [ 0.    0.    6.5 ]]
